[tool.pyright]
typeCheckingMode = "off"
reportMissingImports = "none"
reportGeneralTypeIssues = "none"
reportOptionalMemberAccess = "none"
reportOptionalCall = "none"
reportUnknownArgumentType = "none"
reportUnknownVariableType = "none"
reportMissingTypeStubs = "none"
reportUnknownParameterType = "none"
reportUnknownLambdaType = "none"
reportUnknownMemberType = "none"
reportMissingParameterType = "none"
reportMissingTypeArgument = "none"
reportInvalidTypeVarUse = "none"
reportCallInDefaultInitializer = "none"
reportUnnecessaryIsInstance = "none"
reportUnnecessaryCast = "none"
reportImplicitStringConcatenation = "none"
